"on":
  - push
name: Test
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run lint
  readmeExample:
    name: "[TEST] README example"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run build
      - uses: ./
        id: get_latest_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          query: |
            query release($owner:String!,$repo:String!) {
              repository(owner:$owner,name:$repo) {
                releases(first:1) {
                  nodes {
                    name
                    createdAt
                    tagName
                    description
                  }
                }
              }
            }
          owner: ${{ github.event.repository.owner.name }}
          repo: ${{ github.event.repository.name }}
      - run: "echo latest release: '${{ steps.get_latest_release.outputs.data }}'"
      - id: test_with_int_arg
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          query: |
            query pr_commits($pr_number: Int!) {
              repository(owner: "octokit", name: "graphql-action") {
                pullRequest(number: $pr_number) {
                  commits(first: 10) {
                    edges {
                      node {
                        commit {
                          message
                        }
                      }
                    }
                  }
                }
              }
            }
          pr_number: 1
      - id: check_int_arg
        env:
          JSON_DATA: ${{ steps.test_with_int_arg.outputs.data }}
        run: >
          COMMITS_COUNT=$(echo ${JSON_DATA} | jq
          '.repository.pullRequest.commits[] | length')

          [[ ${COMMITS_COUNT} -eq 6 ]] && exit 0 || exit 1
      - id: test_with_mediaType_previews
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          query: |
            query {
              repository(owner: "octokit", name: "graphql-action") {
                packages(first: 1) {
                  totalCount
                }
              }
            }
          mediaType: '{"previews": ["packages"]}'
      - id: test_with_numeric_string_arg
        name: Test with exponent string argument
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          query: |
            query getFullCommitSha($numericString: String!) {
              repository(owner: "octokit", name: "graphql-action") {
                object(expression: $numericString) {
                  oid
                }
              }
            }
          numericString: '"8635439"'
      - id: check_numeric_string_arg
        env:
          JSON_DATA: ${{ steps.test_with_numeric_string_arg.outputs.data }}
        run: >
          SHA=$(echo ${JSON_DATA} | jq
          '.repository.object.oid')

           [[ "$SHA" = "\"8635439471eba77f992f01a972d2a288c6d2d1cc\"" ]] && exit 0 || exit 1
      - id: test_with_exponent_string_arg
        name: Test with exponent string argument
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          query: |
            query getFullCommitSha($exponentString: String!) {
              repository(owner: "octokit", name: "graphql-action") {
                object(expression: $exponentString) {
                  oid
                }
              }
            }
          exponentString: '"32194e6"'
      - id: check_exponent_string_arg
        env:
          JSON_DATA: ${{ steps.test_with_exponent_string_arg.outputs.data }}
        run: >
          SHA=$(echo ${JSON_DATA} | jq
          '.repository.object.oid')

           [[ "$SHA" = "\"32194e6ec624a1b3f255af32c52e50eef675b1f6\"" ]] && exit 0 || exit 1
